repos:
  - bilardi/aws-docker-host
  - bilardi/diary
  - bilardi/etl-prototype
  - bilardi/github-actions-publish
  - bilardi/python-prototype
  - bilardi/realtime-speech-to-speech
  - bilardi/realtime-transcription
  - bilardi/territory-war